# Generated by Django 4.0.1 on 2022-01-27 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_segundomodelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primermodelo',
            name='campo_uno',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='primermodelo',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
