# Generated by Django 4.0.1 on 2022-01-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0004_alter_segundomodelo_campo_uno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primermodelo',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='segundomodelo',
            name='campo_uno',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segundomodelo',
            name='edad',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
