# Generated by Django 4.0.1 on 2022-02-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='name_img',
            field=models.ImageField(blank='', default='', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='url_image',
            field=models.CharField(max_length=100),
        ),
    ]
