# Generated by Django 4.0.1 on 2022-02-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0002_alter_imagemodel_name_img_alter_imagemodel_url_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='url_image',
            new_name='url_img',
        ),
    ]
